- name: Install and configure Kubernetes cluster
  hosts: all
  become: true
  vars:
    master_packages:
      - wget
      - curl
    worker_packages:
      - curl
  tasks:
    - name: Hello from entry point task
      ansible.builtin.command:
        cmd: echo "Prepare the system"

  roles:
    - common
    - { role: master, when: "'masters' in group_names" }
    - { role: worker, when: "'workers' in group_names" }
