---
- name: Install and configure master, workers
  hosts: all
  become: true

  vars:
    master_packages:
    - wget
    - curl
    worker_packages:
    - curl 


  tasks:
  - name: Disable auto updates on Ubuntu
    ansible.builtin.copy:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";
    when: ansible_distribution == 'Ubuntu'

  - name: Install and configure Control-plane
    include_tasks: "master.yaml"
    when: inventory_hostname in groups["masters"]

  - name: Install and configure Worker-node
    include_tasks: "worker.yaml"
    when: inventory_hostname in groups["workers"]

